import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // Generated by the `powersync-web copy-assets` postinstall — minified
      // vendor bundles and their sourcemaps. `next lint` skipped public/
      // implicitly; the bare `eslint` CLI doesn't, so without this the lint
      // script reports ~1,450 problems in code we don't own.
      "public/@powersync/**",
    ],
  },
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // Vendored verbatim from the React Bits registry (reactbits.dev), which
    // ships looser types and dependency arrays than this project's rules
    // allow. Kept unmodified so re-pulling a component doesn't clobber local
    // fixes — relax the rules here rather than editing upstream code.
    // Anything we adapt for the brand gets copied into src/components/site
    // or src/components/ui and is linted normally.
    files: ["src/components/reactbits/**"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "react-hooks/exhaustive-deps": "off",
      "prefer-const": "off",
      "@typescript-eslint/no-unused-expressions": "off",
    },
  },
];

export default eslintConfig;
